//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")
    /// Resource file `downloadPodCast.json`.
    static let downloadPodCastJson = Rswift.FileResource(bundle: R.hostingBundle, name: "downloadPodCast", pathExtension: "json")
    /// Resource file `loadAnimation.json`.
    static let loadAnimationJson = Rswift.FileResource(bundle: R.hostingBundle, name: "loadAnimation", pathExtension: "json")
    
    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "downloadPodCast", withExtension: "json")`
    static func downloadPodCastJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.downloadPodCastJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "loadAnimation", withExtension: "json")`
    static func loadAnimationJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.loadAnimationJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 19 images.
  struct image {
    /// Image `advanceSec`.
    static let advanceSec = Rswift.ImageResource(bundle: R.hostingBundle, name: "advanceSec")
    /// Image `backSec`.
    static let backSec = Rswift.ImageResource(bundle: R.hostingBundle, name: "backSec")
    /// Image `check`.
    static let check = Rswift.ImageResource(bundle: R.hostingBundle, name: "check")
    /// Image `close`.
    static let close = Rswift.ImageResource(bundle: R.hostingBundle, name: "close")
    /// Image `cloudIcon`.
    static let cloudIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "cloudIcon")
    /// Image `downloadIcon`.
    static let downloadIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "downloadIcon")
    /// Image `headphone`.
    static let headphone = Rswift.ImageResource(bundle: R.hostingBundle, name: "headphone")
    /// Image `home`.
    static let home = Rswift.ImageResource(bundle: R.hostingBundle, name: "home")
    /// Image `iconfacebook`.
    static let iconfacebook = Rswift.ImageResource(bundle: R.hostingBundle, name: "iconfacebook")
    /// Image `iconinstagram`.
    static let iconinstagram = Rswift.ImageResource(bundle: R.hostingBundle, name: "iconinstagram")
    /// Image `icontwitter`.
    static let icontwitter = Rswift.ImageResource(bundle: R.hostingBundle, name: "icontwitter")
    /// Image `iconyoutube`.
    static let iconyoutube = Rswift.ImageResource(bundle: R.hostingBundle, name: "iconyoutube")
    /// Image `pause`.
    static let pause = Rswift.ImageResource(bundle: R.hostingBundle, name: "pause")
    /// Image `play`.
    static let play = Rswift.ImageResource(bundle: R.hostingBundle, name: "play")
    /// Image `podCat`.
    static let podCat = Rswift.ImageResource(bundle: R.hostingBundle, name: "podCat")
    /// Image `profile`.
    static let profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "profile")
    /// Image `starIconFilled`.
    static let starIconFilled = Rswift.ImageResource(bundle: R.hostingBundle, name: "starIconFilled")
    /// Image `starIconNotFilled`.
    static let starIconNotFilled = Rswift.ImageResource(bundle: R.hostingBundle, name: "starIconNotFilled")
    /// Image `stop`.
    static let stop = Rswift.ImageResource(bundle: R.hostingBundle, name: "stop")
    
    /// `UIImage(named: "advanceSec", bundle: ..., traitCollection: ...)`
    static func advanceSec(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.advanceSec, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "backSec", bundle: ..., traitCollection: ...)`
    static func backSec(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.backSec, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "check", bundle: ..., traitCollection: ...)`
    static func check(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.check, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "close", bundle: ..., traitCollection: ...)`
    static func close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.close, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "cloudIcon", bundle: ..., traitCollection: ...)`
    static func cloudIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cloudIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "downloadIcon", bundle: ..., traitCollection: ...)`
    static func downloadIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.downloadIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "headphone", bundle: ..., traitCollection: ...)`
    static func headphone(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.headphone, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "home", bundle: ..., traitCollection: ...)`
    static func home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "iconfacebook", bundle: ..., traitCollection: ...)`
    static func iconfacebook(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.iconfacebook, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "iconinstagram", bundle: ..., traitCollection: ...)`
    static func iconinstagram(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.iconinstagram, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icontwitter", bundle: ..., traitCollection: ...)`
    static func icontwitter(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icontwitter, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "iconyoutube", bundle: ..., traitCollection: ...)`
    static func iconyoutube(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.iconyoutube, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "pause", bundle: ..., traitCollection: ...)`
    static func pause(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pause, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "play", bundle: ..., traitCollection: ...)`
    static func play(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.play, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "podCat", bundle: ..., traitCollection: ...)`
    static func podCat(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.podCat, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "profile", bundle: ..., traitCollection: ...)`
    static func profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "starIconFilled", bundle: ..., traitCollection: ...)`
    static func starIconFilled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.starIconFilled, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "starIconNotFilled", bundle: ..., traitCollection: ...)`
    static func starIconNotFilled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.starIconNotFilled, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "stop", bundle: ..., traitCollection: ...)`
    static func stop(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.stop, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.launchScreen` struct is generated, and contains static references to 0 localization keys.
    struct launchScreen {
      fileprivate init() {}
    }
    
    /// This `R.string.localizable` struct is generated, and contains static references to 27 localization keys.
    struct localizable {
      /// en translation: About
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let sobre = Rswift.StringResource(key: "sobre", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Back
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let voltar = Rswift.StringResource(key: "voltar", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Choose some themes of interest
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let escolhaAlgumTema = Rswift.StringResource(key: "escolhaAlgumTema", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Close
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let fechar = Rswift.StringResource(key: "fechar", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Download PodCat Podcast Player Now on the App Store:
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let downloadText = Rswift.StringResource(key: "downloadText", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Episode
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let episodio = Rswift.StringResource(key: "episodio", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Language:
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let idiomaIndication = Rswift.StringResource(key: "idiomaIndication", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Location:
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let localizacaoIndication = Rswift.StringResource(key: "localizacaoIndication", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: More
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let mais = Rswift.StringResource(key: "mais", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: My PodCasts
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let meuspodcasts = Rswift.StringResource(key: "meuspodcasts", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: My Podcasts
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let meusPodCast = Rswift.StringResource(key: "meusPodCast", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: PodCast
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let podcast = Rswift.StringResource(key: "podcast", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: PodCat
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let appName = Rswift.StringResource(key: "appName", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: PodCat is a podcast player where you can stream or download your favorite podcasts anytime, anywhere.  NYou can download a podcast to listen offline, bookmark a podcast to find it faster, search over 741,919 podcasts and 49,639,147 episodes  nThe app is completely Free and No Ads
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let aboutString = Rswift.StringResource(key: "aboutString", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Profile
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let perfil = Rswift.StringResource(key: "perfil", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Rate us
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let avalieNos = Rswift.StringResource(key: "avalieNos", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Remove Data
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let removeData = Rswift.StringResource(key: "removeData", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: START
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let iniciar = Rswift.StringResource(key: "iniciar", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Search
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let buscar = Rswift.StringResource(key: "buscar", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Settings
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let configuracoes = Rswift.StringResource(key: "configuracoes", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Share PodCat
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let sharePodCat = Rswift.StringResource(key: "sharePodCat", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Start
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let inicio = Rswift.StringResource(key: "inicio", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Subjects
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let assuntos = Rswift.StringResource(key: "assuntos", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: Subscriptions
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let inscricoes = Rswift.StringResource(key: "inscricoes", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: english
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let ingles = Rswift.StringResource(key: "ingles", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: portuguese
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let portugues = Rswift.StringResource(key: "portugues", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      /// en translation: spanish
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static let espanhol = Rswift.StringResource(key: "espanhol", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "pt-BR", "es", "en-AU", "en-GB", "en-IN", "es-419", "pt-PT"], comment: nil)
      
      /// en translation: About
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func sobre(_: Void = ()) -> String {
        return NSLocalizedString("sobre", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Back
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func voltar(_: Void = ()) -> String {
        return NSLocalizedString("voltar", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Choose some themes of interest
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func escolhaAlgumTema(_: Void = ()) -> String {
        return NSLocalizedString("escolhaAlgumTema", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Close
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func fechar(_: Void = ()) -> String {
        return NSLocalizedString("fechar", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Download PodCat Podcast Player Now on the App Store:
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func downloadText(_: Void = ()) -> String {
        return NSLocalizedString("downloadText", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Episode
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func episodio(_: Void = ()) -> String {
        return NSLocalizedString("episodio", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Language:
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func idiomaIndication(_: Void = ()) -> String {
        return NSLocalizedString("idiomaIndication", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Location:
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func localizacaoIndication(_: Void = ()) -> String {
        return NSLocalizedString("localizacaoIndication", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: More
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func mais(_: Void = ()) -> String {
        return NSLocalizedString("mais", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: My PodCasts
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func meuspodcasts(_: Void = ()) -> String {
        return NSLocalizedString("meuspodcasts", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: My Podcasts
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func meusPodCast(_: Void = ()) -> String {
        return NSLocalizedString("meusPodCast", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: PodCast
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func podcast(_: Void = ()) -> String {
        return NSLocalizedString("podcast", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: PodCat
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func appName(_: Void = ()) -> String {
        return NSLocalizedString("appName", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: PodCat is a podcast player where you can stream or download your favorite podcasts anytime, anywhere.  NYou can download a podcast to listen offline, bookmark a podcast to find it faster, search over 741,919 podcasts and 49,639,147 episodes  nThe app is completely Free and No Ads
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func aboutString(_: Void = ()) -> String {
        return NSLocalizedString("aboutString", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Profile
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func perfil(_: Void = ()) -> String {
        return NSLocalizedString("perfil", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Rate us
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func avalieNos(_: Void = ()) -> String {
        return NSLocalizedString("avalieNos", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Remove Data
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func removeData(_: Void = ()) -> String {
        return NSLocalizedString("removeData", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: START
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func iniciar(_: Void = ()) -> String {
        return NSLocalizedString("iniciar", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Search
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func buscar(_: Void = ()) -> String {
        return NSLocalizedString("buscar", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Settings
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func configuracoes(_: Void = ()) -> String {
        return NSLocalizedString("configuracoes", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Share PodCat
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func sharePodCat(_: Void = ()) -> String {
        return NSLocalizedString("sharePodCat", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Start
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func inicio(_: Void = ()) -> String {
        return NSLocalizedString("inicio", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Subjects
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func assuntos(_: Void = ()) -> String {
        return NSLocalizedString("assuntos", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Subscriptions
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func inscricoes(_: Void = ()) -> String {
        return NSLocalizedString("inscricoes", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: english
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func ingles(_: Void = ()) -> String {
        return NSLocalizedString("ingles", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: portuguese
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func portugues(_: Void = ()) -> String {
        return NSLocalizedString("portugues", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: spanish
      /// 
      /// Locales: en, pt-BR, es, en-AU, en-GB, en-IN, es-419, pt-PT
      static func espanhol(_: Void = ()) -> String {
        return NSLocalizedString("espanhol", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
