//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `loadAnimation.json`.
    static let loadAnimationJson = Rswift.FileResource(bundle: R.hostingBundle, name: "loadAnimation", pathExtension: "json")
    
    /// `bundle.url(forResource: "loadAnimation", withExtension: "json")`
    static func loadAnimationJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.loadAnimationJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 11 images.
  struct image {
    /// Image `Mario`.
    static let mario = Rswift.ImageResource(bundle: R.hostingBundle, name: "Mario")
    /// Image `advanceSec`.
    static let advanceSec = Rswift.ImageResource(bundle: R.hostingBundle, name: "advanceSec")
    /// Image `backSec`.
    static let backSec = Rswift.ImageResource(bundle: R.hostingBundle, name: "backSec")
    /// Image `check`.
    static let check = Rswift.ImageResource(bundle: R.hostingBundle, name: "check")
    /// Image `close`.
    static let close = Rswift.ImageResource(bundle: R.hostingBundle, name: "close")
    /// Image `headphone`.
    static let headphone = Rswift.ImageResource(bundle: R.hostingBundle, name: "headphone")
    /// Image `home`.
    static let home = Rswift.ImageResource(bundle: R.hostingBundle, name: "home")
    /// Image `pause`.
    static let pause = Rswift.ImageResource(bundle: R.hostingBundle, name: "pause")
    /// Image `play`.
    static let play = Rswift.ImageResource(bundle: R.hostingBundle, name: "play")
    /// Image `profile`.
    static let profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "profile")
    /// Image `stop`.
    static let stop = Rswift.ImageResource(bundle: R.hostingBundle, name: "stop")
    
    /// `UIImage(named: "Mario", bundle: ..., traitCollection: ...)`
    static func mario(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.mario, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "advanceSec", bundle: ..., traitCollection: ...)`
    static func advanceSec(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.advanceSec, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "backSec", bundle: ..., traitCollection: ...)`
    static func backSec(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.backSec, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "check", bundle: ..., traitCollection: ...)`
    static func check(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.check, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "close", bundle: ..., traitCollection: ...)`
    static func close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.close, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "headphone", bundle: ..., traitCollection: ...)`
    static func headphone(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.headphone, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "home", bundle: ..., traitCollection: ...)`
    static func home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "pause", bundle: ..., traitCollection: ...)`
    static func pause(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pause, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "play", bundle: ..., traitCollection: ...)`
    static func play(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.play, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "profile", bundle: ..., traitCollection: ...)`
    static func profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "stop", bundle: ..., traitCollection: ...)`
    static func stop(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.stop, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 10 localization keys.
    struct localizable {
      /// Value: Assuntos
      static let assuntos = Rswift.StringResource(key: "assuntos", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Buscar
      static let buscar = Rswift.StringResource(key: "buscar", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Escolha alguns temas de seu interesse
      static let escolhaAlgumTema = Rswift.StringResource(key: "escolhaAlgumTema", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Fechar
      static let fechar = Rswift.StringResource(key: "fechar", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: INICIAR
      static let iniciar = Rswift.StringResource(key: "iniciar", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Inicio
      static let inicio = Rswift.StringResource(key: "inicio", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Mais
      static let mais = Rswift.StringResource(key: "mais", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Meus Podcasts
      static let meusPodCast = Rswift.StringResource(key: "meusPodCast", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Perfil
      static let perfil = Rswift.StringResource(key: "perfil", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Voltar
      static let voltar = Rswift.StringResource(key: "voltar", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Assuntos
      static func assuntos(_: Void = ()) -> String {
        return NSLocalizedString("assuntos", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Buscar
      static func buscar(_: Void = ()) -> String {
        return NSLocalizedString("buscar", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Escolha alguns temas de seu interesse
      static func escolhaAlgumTema(_: Void = ()) -> String {
        return NSLocalizedString("escolhaAlgumTema", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Fechar
      static func fechar(_: Void = ()) -> String {
        return NSLocalizedString("fechar", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: INICIAR
      static func iniciar(_: Void = ()) -> String {
        return NSLocalizedString("iniciar", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Inicio
      static func inicio(_: Void = ()) -> String {
        return NSLocalizedString("inicio", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Mais
      static func mais(_: Void = ()) -> String {
        return NSLocalizedString("mais", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Meus Podcasts
      static func meusPodCast(_: Void = ()) -> String {
        return NSLocalizedString("meusPodCast", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Perfil
      static func perfil(_: Void = ()) -> String {
        return NSLocalizedString("perfil", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Voltar
      static func voltar(_: Void = ()) -> String {
        return NSLocalizedString("voltar", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
